name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.0"
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build

      - name: Deploy application
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: build
          branch: gh-pages
